[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Build hooks for triggering rebuilds
[[build.hooks]]
  type = "pre_build"
  command = "node scripts/generate-css.js"

# Functions configuration
[functions]
  directory = "app/api"
